Add missing libraries
resulting in:

/runner/_work/kcrypt-discovery-challenger/kcrypt-discovery-challenger/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
-: # github.com/google/go-tpm-tools/simulator/internal
In file included from /home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/LibSupport.h:65,
                 from /home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Tpm.h:47,
                 from /home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/internal/internal_cgo.go:45:
/home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Ossl/TpmToOsslSym.h:47:10: fatal error: openssl/aes.h: No such file or directory
   47 | #include <openssl/aes.h>
      |          ^~~~~~~~~~~~~~~

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>