Remove attestation with KMS
[WIP] Split with-TPM and without-TPM flows

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Introduce a cli interface to interace with the challenger client

This will make debugging easier both while developing and in production.
No need to use it through the kcrypt binary anymore, because we might
not actually care about decrypting the disks but rather about getting
the passphrase from the KMS.

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Use a KairosLogger consistently

in plugin mode: log only to a file and journal and in "debug" level by
default

in cli mode: respect the `--debug` flag and write to the stdout

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove legacy methods from old flow

TODO: Implemnt TOFU on the server

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Implement TOFU flow on the server

and fix some issues with the data we send back and forth between the
client and the server

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Treat and empty passphrase as an error

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove unecessary patches in deployment

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Use specific PCRs in tpm quote

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Don't shot trace log when a security violation occurs

because it's not an application error but rather normal behaviour

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Handle PCR validation errors gracefully

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Don't use the (now removed) redundant field

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove unecessary wrapper

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Move path to a constant

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

[TMP] use a replace that points to a branch (instead of localy dir)

Point to this: https://github.com/kairos-io/tpm-helpers/pull/7

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove meaningless test

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Migrate to cobra cli for better code organization

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Avoid global vars

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Allow the user to cleanup NV indexes

e.g. to reset the passphrase stored on the TPM for local encryption

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove stubbed version and fix tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add TODO in README for selective enrollement

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Refactor wall-of-text method to one with better narrative

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove enrollement reporting on authentication request

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Reuse a secret then it's there and ignore missing PCRs

This allows the operator to re-use an existing passphrase but let the
sealed volume be re-created automatically (so decryption can still
happen, we don't loose the original passphrase).

Also allows the operator to skip a PCR (e.g. 11) if they want to by
simply removing it after the initial enrollement or by manuall creating
the initial sealed volume but only with the PCRs they are interested in
by setting those to empty strings. This is useful if a PCR is expected
to change often, e.g. PCR 11 because of kernel upgrades.

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Explain the various scenarios

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Reject early when TPM is quarantined

and update the README with remaining TODOs (only e2e tests missing)

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add mermaid diagram explainin the attestation flow

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

[WIP] Implement e2e tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Merge multiple tests into one

to save time from setup of VMs and such

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Make sure kcrypt-challenger respect the `manual-install` config

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix config in tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix plugin trying to run `--debug` event and not logging to files

Args[0] is no longer guaranteed to be the event's name. We have a proper
command now.

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

[DEBUG] try to print the kcrypt logs on failure

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Set plugin mode to "debug" to see what's going on

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Use safe kube names, output the passphrase to stdout

and improve test logging on failure

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

When another partition is request for an enrolled tpm, just update

instead of trying to create a new sealed volume

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

go mod tidy (after rebase)

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Use nv index to store the AK blob

because during initramfs there is no (unencrypted) persistent storage to
use for a file.

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Use transient AK keys and avoid storing it

because we don't have a persistent storage available during initramfs
and NV indices are not big enough to store the AK blob. After all, we
verify the EK so we just validate that the AK is generated by that EK,
no need to enroll the AK.

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Use the new attestation pkg

which has cleaner API and responsibilities

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Verify the PCRs against the quote

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove AK references

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix pem

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Try with CGO_ENABLED=1

because tests are failing with:

Will run 3 of 3 specs
------------------------------
• [FAILED] [0.000 seconds]
Remote attestation end-to-end [It] client and server roundtrip
/runner/_work/kcrypt-discovery-challenger/kcrypt-discovery-challenger/pkg/attestation/attestation_test.go:21

  [FAILED] Unexpected error:
      <*fmt.wrapError | 0xc000081b00>:
      opening TPM: startup: using the simulator requires building with CGO
      {
          msg: "opening TPM: startup: using the simulator requires building with CGO",
          err: <*fmt.wrapError | 0xc000081ae0>{
              msg: "startup: using the simulator requires building with CGO",
              err: <*errors.errorString | 0xc000037b90>{
                  s: "using the simulator requires building with CGO",
              },
          },
      }
  occurred
  In [It] at: /runner/_work/kcrypt-discovery-challenger/kcrypt-discovery-challenger/pkg/attestation/attestation_test.go:24 @ 10/01/25 15:36:06.699

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add gcc in tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add missing libraries

resulting in:

/runner/_work/kcrypt-discovery-challenger/kcrypt-discovery-challenger/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
-: # github.com/google/go-tpm-tools/simulator/internal
In file included from /home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/LibSupport.h:65,
                 from /home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Tpm.h:47,
                 from /home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/internal/internal_cgo.go:45:
/home/runner/go/pkg/mod/github.com/google/go-tpm-tools@v0.4.4/simulator/ms-tpm-20-ref/TPMCmd/tpm/include/Ossl/TpmToOsslSym.h:47:10: fatal error: openssl/aes.h: No such file or directory
   47 | #include <openssl/aes.h>
      |          ^~~~~~~~~~~~~~~

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove debug logs that pollute the output

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix selective enrollement of EK and add tests and docs

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Wait for 30 seconds for network

because that's possibly the reason why the tests fail, dns is not ready
and everything goes fubar

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add missing import

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix identation

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Read kcrypt configuration from /proc/cmdline

because when COS_OEM is encrypted, we can't read it from there.
Needs: https://github.com/kairos-io/kairos-agent/pull/988

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Get kcrypt config from payload

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

[TMP] Debugging targets (remove before merging?)

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Stick to a JSON api, fix and improve tests

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Fix linter warning/suggestions and remove unused code

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add "info" command to kcrypt cli to help debugging

It prints the TPM hash, the EK public key and the requested PCRs
(defaults to 0,7,11)

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Defer PCR enrollement for after reboot

because the values of the live system may not be the same as the
installed system (e.g. because user installed with `--source` flag
pointing to another image)

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Bump tpm-helpers

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove Earthly

and migrate to Make targets with Dockerfile

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Use kairos-sdk ghw structs instead of upstream ones

and adapt to the changed payload that doesn't include unecessary
information

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add missing deps, make keys dir mandatory in Make target and bump go.mod

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

PR improvements

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove local passphrase logic

because it's now implemented in kairos-sdk (used by kairos-agent and
immucore). Also move the cleanup method to the kairos-agent:

https://github.com/kairos-io/kairos-agent/pull/1027

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add shared tpm-device flag and respect it when set.

Also read the config using the collector for the various command that
might need to read NVIndex, CIndex and TPMDevice (they were using an
empty config so far)

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Remove tests that don't do anything

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Cleanup

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

PR fixes

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Add README.md section to explain the Makefile usage

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>

Potential fix for code scanning alert no. 72: Clear-text logging of sensitive information

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>